server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # Thần chú cứu rỗi SPA khi F5 nằm ở đây
        try_files $uri $uri/ /index.html;
    }

    # Cấu hình thêm để tối ưu hóa lỗi 50x nếu cần
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}